In [1]:
# univariate bidirectional lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional

# split a univariate sequence
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

c:\Users\dinit\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


[[101.30982]]


In [2]:
X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

model = Sequential([
    LSTM(50, activation='relu', return_sequences=True, input_shape=(timesteps, features)),
    Dense(1) 
])

model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(, y_train, epochs=20, batch_size=8, verbose=1)

# Test the model
y_pred = model.predict(X_test)

# Print first few predictions
print("Predicted values:", y_pred[:5].flatten())
print("Actual values:", y_test[:5].flatten())


Epoch 1/20


c:\Users\dinit\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


50/50 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1782
Epoch 2/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0998
Epoch 3/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1008
Epoch 4/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0892
Epoch 5/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0850
Epoch 6/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0791
Epoch 7/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0846
Epoch 8/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0749
Epoch 9/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0822
Epoch 10/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0799
Epoch 11/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0768
Epoch 12/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0847
Epoch 13/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0786
Epoch 14/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0772
Epoch 15/20
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0879
Epoch 16/20
50/50 ━━━━━━━━━━━━

In [11]:
X_test

array([[[0.72999831, 0.184512  , 0.34663969, ..., 0.11654669,
         0.70956772, 0.23034416],
        [0.41447673, 0.03286273, 0.13590738, ..., 0.97218297,
         0.59907151, 0.24171373],
        [0.32765503, 0.31983592, 0.32649433, ..., 0.02213916,
         0.21883468, 0.1074714 ],
        [0.78544503, 0.11249796, 0.72422824, ..., 0.23576151,
         0.89468117, 0.04525831],
        [0.20181961, 0.75204693, 0.70937793, ..., 0.19571341,
         0.51606182, 0.9102272 ]],

       [[0.04354658, 0.76580409, 0.57247323, ..., 0.14364737,
         0.91288175, 0.66895308],
        [0.43798602, 0.57325957, 0.74561391, ..., 0.63966427,
         0.4157279 , 0.59459845],
        [0.4199858 , 0.15299579, 0.46942675, ..., 0.41468771,
         0.78629393, 0.41285927],
        [0.69653079, 0.50721368, 0.24122313, ..., 0.06706563,
         0.50293394, 0.49956216],
        [0.7069009 , 0.74475069, 0.72779149, ..., 0.59721269,
         0.94724788, 0.19289374]],

       [[0.9057721 , 0.05345551, 0.3

array([[0.09237084],
       [0.06075373],
       [0.60419195],
       [0.96611632],
       [0.50272131],
       [0.05151523],
       [0.22121866],
       [0.24479291],
       [0.33785713],
       [0.04360338],
       [0.9048927 ],
       [0.51556394],
       [0.67093079],
       [0.06717284],
       [0.05411547],
       [0.58646777],
       [0.88729601],
       [0.528482  ],
       [0.87781917],
       [0.81099127],
       [0.07585379],
       [0.20195747],
       [0.65771067],
       [0.44350138],
       [0.29069981],
       [0.41863386],
       [0.44519965],
       [0.91055225],
       [0.10345828],
       [0.27973075],
       [0.53756482],
       [0.69828693],
       [0.63063729],
       [0.94164274],
       [0.79560892],
       [0.55707684],
       [0.21468269],
       [0.45087423],
       [0.69338224],
       [0.83796217],
       [0.95973622],
       [0.60545277],
       [0.52691937],
       [0.01769192],
       [0.07209907],
       [0.156105  ],
       [0.05475993],
       [0.400

In [13]:
import tensorflow as tf
import tensorflow.keras.backend as K

single_LSTM = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(64, activation='tanh', return_sequences=False,
                         input_shape=(5,10)),
    tf.keras.layers.Dense(1)  
])

single_LSTM.compile(optimizer='adam', loss='mse', metrics=['mse'])  # MSE loss, MAE metric

 

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_true - y_pred)))

single_LSTM.compile(optimizer='adam', loss=rmse)

In [15]:
single_LSTM.fit(X_train,y_train , epochs=50)

Epoch 1/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.5480 - mse: 0.3183
Epoch 2/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3270 - mse: 0.1092
Epoch 3/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2864 - mse: 0.0823
Epoch 4/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2886 - mse: 0.0834
Epoch 5/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2822 - mse: 0.0800
Epoch 6/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2752 - mse: 0.0771
Epoch 7/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2816 - mse: 0.0798
Epoch 8/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2891 - mse: 0.0839
Epoch 9/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2889 - mse: 0.0838
Epoch 10/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2838 - mse: 0.0811
Epoch 11/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2830 - mse: 0.0807
Epoch 12/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2881 - mse: 0.0835
Epoch 13/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11