In [13]:
# univariate bidirectional lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional

# split a univariate sequence
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model


In [14]:
import tensorflow.keras.backend as K

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_true - y_pred)))

In [15]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss=rmse, metrics=['mse'])
# fit model

In [16]:

model.fit(X, y, epochs=200, verbose=1)


Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 69.8591 - mse: 4880.2988
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 69.3127 - mse: 4804.2441
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 68.7582 - mse: 4727.6865
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 68.1959 - mse: 4650.6748
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 67.6262 - mse: 4573.3086
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 67.0501 - mse: 4495.7202
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 66.4685 - mse: 4418.0547
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 65.8829 - mse: 4340.5503
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 65.2954 - mse: 4263.4937
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 64.7087 - mse: 4187.2158
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 64.1264 - mse: 4112.1968
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 63.5517 - mse: 4038.8213
Ep

In [17]:
X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [18]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

model = Sequential([
    LSTM(50, activation='relu', return_sequences=True, input_shape=(timesteps, features)),
    Dense(1) 
])

model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(x, y_train, epochs=20, batch_size=8, verbose=1)

# Test the model
y_pred = model.predict(X_test)

# Print first few predictions
print("Predicted values:", y_pred[:5].flatten())
print("Actual values:", y_test[:5].flatten())


NameError: name 'timesteps' is not defined

In [ ]:
X_test

array([[[0.72999831, 0.184512  , 0.34663969, ..., 0.11654669,
         0.70956772, 0.23034416],
        [0.41447673, 0.03286273, 0.13590738, ..., 0.97218297,
         0.59907151, 0.24171373],
        [0.32765503, 0.31983592, 0.32649433, ..., 0.02213916,
         0.21883468, 0.1074714 ],
        [0.78544503, 0.11249796, 0.72422824, ..., 0.23576151,
         0.89468117, 0.04525831],
        [0.20181961, 0.75204693, 0.70937793, ..., 0.19571341,
         0.51606182, 0.9102272 ]],

       [[0.04354658, 0.76580409, 0.57247323, ..., 0.14364737,
         0.91288175, 0.66895308],
        [0.43798602, 0.57325957, 0.74561391, ..., 0.63966427,
         0.4157279 , 0.59459845],
        [0.4199858 , 0.15299579, 0.46942675, ..., 0.41468771,
         0.78629393, 0.41285927],
        [0.69653079, 0.50721368, 0.24122313, ..., 0.06706563,
         0.50293394, 0.49956216],
        [0.7069009 , 0.74475069, 0.72779149, ..., 0.59721269,
         0.94724788, 0.19289374]],

       [[0.9057721 , 0.05345551, 0.3

array([[0.09237084],
       [0.06075373],
       [0.60419195],
       [0.96611632],
       [0.50272131],
       [0.05151523],
       [0.22121866],
       [0.24479291],
       [0.33785713],
       [0.04360338],
       [0.9048927 ],
       [0.51556394],
       [0.67093079],
       [0.06717284],
       [0.05411547],
       [0.58646777],
       [0.88729601],
       [0.528482  ],
       [0.87781917],
       [0.81099127],
       [0.07585379],
       [0.20195747],
       [0.65771067],
       [0.44350138],
       [0.29069981],
       [0.41863386],
       [0.44519965],
       [0.91055225],
       [0.10345828],
       [0.27973075],
       [0.53756482],
       [0.69828693],
       [0.63063729],
       [0.94164274],
       [0.79560892],
       [0.55707684],
       [0.21468269],
       [0.45087423],
       [0.69338224],
       [0.83796217],
       [0.95973622],
       [0.60545277],
       [0.52691937],
       [0.01769192],
       [0.07209907],
       [0.156105  ],
       [0.05475993],
       [0.400

In [ ]:
import tensorflow as tf
import tensorflow.keras.backend as K

single_LSTM = tf.keras.models.Sequential([
    tf.keras.layers.LSTM(64, activation='tanh', return_sequences=False,
                         input_shape=(5,10)),
    tf.keras.layers.Dense(1)  
])

single_LSTM.compile(optimizer='adam', loss='mse', metrics=['mse'])  # MSE loss, MAE metric

 

def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_true - y_pred)))

single_LSTM.compile(optimizer='adam', loss=rmse)

In [ ]:
single_LSTM.fit(X_train,y_train , epochs=50)

Epoch 1/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.5480 - mse: 0.3183
Epoch 2/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3270 - mse: 0.1092
Epoch 3/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2864 - mse: 0.0823
Epoch 4/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2886 - mse: 0.0834
Epoch 5/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2822 - mse: 0.0800
Epoch 6/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2752 - mse: 0.0771
Epoch 7/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2816 - mse: 0.0798
Epoch 8/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2891 - mse: 0.0839
Epoch 9/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2889 - mse: 0.0838
Epoch 10/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2838 - mse: 0.0811
Epoch 11/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2830 - mse: 0.0807
Epoch 12/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2881 - mse: 0.0835
Epoch 13/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11